#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

echo "Positive filters:"
diff <(fls Lf ../.fixtures/testdir) <(fls fL ../.fixtures/testdir)

echo "Negative filters:"
diff <(fls ^Ld ../.fixtures/testdir) <(fls ^dL ../.fixtures/testdir)

echo "Combined filters:"
diff <(fls fr^sw ../.fixtures/testdir) <(fls rf^ws ../.fixtures/testdir)
