#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH


# Using a glob
echo "Hidden items with glob:"
diff <(fls ../.fixtures/testdir/.* | fgrep -vx $'.DS_Store\n..\n.') - <<'EOF' || exit
.zero
EOF

echo "Hidden items (also) reprorted with -A:"
diff <(fls -A ../.fixtures/testdir | fgrep -vx '.DS_Store' | grep -E '^\.') - <<'EOF' || exit
.zero
EOF

echo "Hidden items (also) reprorted with -a:"
diff <(fls -a ../.fixtures/testdir | fgrep -vx '.DS_Store' | grep -E '^\.') - <<'EOF' || exit
.
..
.zero
EOF
