#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

echo "Files that are empty:"
diff <(fls fe ../.fixtures/testdir) - <<'EOF' || exit
c
two (2)
EOF

echo "Files that are nonempty and not symlinks:"
diff <(fls f^el ../.fixtures/testdir) - <<'EOF' || exit
one
EOF

echo "Items that are nonempty and neither files nor symlinks:"
diff <(fls ^efl ../.fixtures/testdir) - <<'EOF' || exit
subd
EOF

# Files (f) that are readable (r) but neither (^) nonempty(s) nor writable (w) - in other words: both empty and non-writable.
chmod -w ../.fixtures/testdir/'two (2)' # to be sure, let's make sure the test file is not writable.
echo "Files that are readable, not nonempty (i.e., empty), and not writable:"
diff <(fls fr^sw ../.fixtures/testdir) - <<'EOF' || exit
two (2)
EOF
