#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Make sure empty dir. exists (Git will not store it.)
mkdir -p ../.fixtures/testdir/subd-empty

diff <(fls d ../.fixtures/testdir) - <<EOF || exit
subd
subd-empty
subdl
EOF
