#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

echo "The set of non-directories matches the set of files + the dead symlink"
diff <(fls ^d ../.fixtures/testdir) - <<'EOF' || exit
c
dead-symlink
one
onel
two (2)
EOF

echo "Items that are NOT a directory and NOT a symlink (i.e., neither a directory nor a symlink)"
diff <(fls ^dL ../.fixtures/testdir) - <<'EOF' || exit
c
one
two (2)
EOF
