#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Symlinks, whether to a file or dir.
echo "Symlinks, whether to a file or dir or dead:"
diff <(fls l ../.fixtures/testdir) - <<EOF || exit
dead-symlink
onel
subdl
EOF

# Symlinks to *files*.
echo "Symlinks to files:"
diff <(fls lf ../.fixtures/testdir) - <<EOF || exit
onel
EOF

# Symlinks to *dirs*.
echo "Symlinks to dirs.:"
diff <(fls ld ../.fixtures/testdir) - <<EOF || exit
subdl
EOF

# Equivalence of l, L, and h
echo "l is the same as L:"
diff <(fls l ../.fixtures/testdir) <(fls L ../.fixtures/testdir) || exit
echo "l is the same as h:"
diff <(fls l ../.fixtures/testdir) <(fls h ../.fixtures/testdir) || exit
